sudo: required
language: node_js
node_js:
  - 7
services:
  - docker
before-install:
  - docker build -t IMG1 .

scriptes:
  - docker run IMG1
deploy:
  provider: elasticbeanstalk
  region:  "eu-west-1"
  app: "docker-react-test"
  env: "DockerReactTest-env"
  bucket_name: "elasticbeanstalk-eu-west-1-021160874513"
  bucket_path: "docker-react-test"
  on:
    branch: master
    password: "Hd0iTbTkoAbpe912n2yFO51wh7X2LlYlk/1Fd2Nj"